export const AGREGAR_TAREA = 'AGREGAR_PRODUCTO'
export const AGREGAR_TAREA_EXITO = 'AGREGAR_PRODUCTO_EXITO'
export const AGREGAR_TAREA_ERROR = 'AGREGAR_PRODUCTO_ERROR'

export const COMENZAR_DESCARGAR_TAREAS = 'COMENZAR_DESCARGAR_PRODUCTOS'
export const DESCARGA_TAREAS_EXITO = 'DESCARGA_PRODUCTOS_EXITO'
export const DESCARGA_TAREAS_ERROR = 'DESCARGA_PRODUCTOS_ERROR'

export const ELIMINAR_TAREA = 'ELIMINAR_PRODUCTO'
export const ELIMINAR_TAREA_EXITO = 'ELIMINAR_PRODUCTO_EXITO'
export const ELIMINAR_TAREA_ERROR = 'ELIMINAR_PRODUCTO_ERROR'

export const OBTENER_TAREA_EDITAR = 'OBTENER_PRODUCTO_EDITAR'
export const COMENZAR_EDICION_TAREA = 'COMENZAR_EDICION_PRODUCTO'
export const TAREA_EDITADO_EXITO = 'PRODUCTO_EDITADO_EXITO'
export const TAREA_EDITADO_ERROR = 'PRODUCTO_EDITADO_ERROR'
